spring:
  cloud:
    config: false
    azure:
      cosmos:
        database: Users
        endpoint: https://localhost:8081/
        populate-query-metrics: true
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        containerName: AnandTandemUsers
springdoc:
  api-docs:
    path: /api-docs
management:
  health:
    db:
      enabled: true
    defaults:
      enabled: true
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
      sensitive: false
      group:
        custom:
          show-components: always
          show-details: always