spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config: false
    azure:
      cosmos:
        database: user-collaction1
        endpoint: https://localhost:8081
        populate-query-metrics: true
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        containerName: AyushTandemUsersSpringBoot
